### ISSUE TITLE
Texto em destaque sendo trocado por um novo texto

### ISSUE THREAD

**Issue by thiagonf** [labhackercd/new-wikilegis#205]
Ao selecionar um texto em um projeto de lei aparece uma modal no inferior da tela com o texto selecionado, nesta modal há um span que mostra qual texto foi selecionado da do projeto de lei. Em baixo do campo de span há um input text, caso digite um texto nesse input e selecione o mesmo o texto do span está mudando e não é para mudar.

**Comment by joaopaulonsoares** [comment]
Issue resolvida.
