### ISSUE TITLE
US02 - Eu, como servidor, desejo adicionar uma versão final do texto para dar feedback da participaçao

### ISSUE THREAD

**Issue by thiagonf** [labhackercd/new-wikilegis#227]
**Feature:**  F01 - Inserir texto final da proposta
**Tracking:** E01F01US02

**Critérios de aceitação**
- [x] Botão na toolbar para realizar o feedback.

- [x] Modal que possibilite selecionar uma versão final do texto.

- [x] Ao enviar feedback trocar o comportamento do botão que chama a modal. O novo comportamento deverá mostrar que o documento está aguardado análise do deputado.

**Comment by erivanio** [comment]
Fechado no commit #244
