### ISSUE TITLE
US04 - Eu, como cidadão, desejo saber há quanto tempo cada projeto está aguardando feedback, para pressionar o deputado

### ISSUE THREAD

**Issue by thiagonf** [labhackercd/new-wikilegis#233]
**Feature:**  F01 - Inserir texto final da proposta
**Tracking:** E01F01US04

**Critérios de aceitação**
- [x] Aviso de aguardando feedback no card da listagem da home. (Label)

- [x] Contador no card de quantos dias o documento está aguardadndo feedback.

**Comment by oteomoura** [comment]
Issue fechada no commit #245
