### ISSUE TITLE
US02 - Eu, como cidadão, desejo ver o mapa de calor, para entender melhor a participação

### ISSUE THREAD

**Issue by oteomoura** [labhackercd/new-wikilegis#237]
**Feature**:  F04 - Estatísticas para a sociedade em geral
**Tracking**: E01F04US02

**Critérios de aceitação**

- [x] Criar um minimap do mapa de calor de participação.

- [x] Criar um minimap do mapa de calor de votos.

- [x] Criar um minimap do mapa de calor de opiniões.

**Comment by erivanio** [comment]
Resolvido no commit #252
