### ISSUE TITLE
TS-AjustarDependencias

### ISSUE THREAD

**Issue by joaopaulonsoares** [labhackercd/new-wikilegis#350]
Eu, como desenvolvedor, desejo ajustar as versões das dependências do projeto para facilitar a instalação da aplicação;

Critérios de aceitação

- [x] Colocar versões fixas para as dependências;
- [x] Remover dependências não utilizadas;
- [x] Atualizar Pipfile.lock

**Comment by erivanio** [comment]
Para atualizar o README:

INSTALAR DEPÊNDENCIAS
1 - Instalar pip - sudo apt install python3-pip
2 - Instalar pipenv - sudo pip install pipenv
3 - Instalar nodejs - sudo apt install nodejs
4 - Instalar npm - sudo apt install npm

CONFIGURAR PIPENV
5 - Descobrir onde está o python3 - whereis python
6 - Colocar a versão do python3 no pipenv - pipenv install --python /usr/bin/python3.8
7 - Entrar na pipenv - pipenv shell

EXECUTAR PROJETO
8 - Criar o banco - python3 src/manage.py migrate
9 - Copiar urls para os arquivos estáticos - python3 src/manage.py collectstatic_js_reverse
10 - Instalar dependências npm - npm install
11 - Executar runserver - python3 src/manage.py runserver
